### PR TITLE
Fixed compile error

### PR DESCRIPTION
**Pull request by schnabel45**
I opened issue #1, this request fixes compilation errors by converting from character literals to strings where appropriate (line 13, 18, 19). Added a missing semicolin to like 19. Added the status string to the class definition in line 26. This class now successfully compiles on DotNet 3.1.301, I'm not sure if it was successfully compiling on older version or not, but I can't imagine it was.

### CODE REVIEW

**Comment by petertuton** [comment]
FYI, I opened issue [#4](https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/issues/4) due to additional errors with the use of the `status` property.

**Comment by rajmsft** [comment]
Error Compiling - Too many characters in character literal; The ResponseContent.cs is still nt handling the status ...
